### ISSUE TITLE
MacOS cp Error - No such file or directory

### ISSUE THREAD

**Issue by eeease** [StephenHodgson/UnityCI#6]
This has been working wonderfully as part of my Azure CI/CD workflow.
Recently (26 February 2024), my MacOS hosted agents are failing at line 79:

>     sudo cp -rf "`"$dmgAppPath`"" "/Applications"`

I get the following error

>     cp: "/Volumes/Unity Hub 3.7.0/Unity Hub.app": No such file or directory

Which leads to later errors installing Unity.

Note: The previous Write-Host line seems to be printing correctly:

>     Write-Host $dmgAppPath

prints `/Volumes/Unity Hub 3.7.0/Unity Hub.app`

which is what it has always printed on successful runs.

I've tried a few things but it's tough to see what's going on in a temporary remote (cloud) machine.  I'll continue troubleshooting but I figure I'd drop a line here to see if anyone has come up against the same issue.

**Comment by StephenHodgson** [comment]
This is a test repo. Use https://github.com/RageAgainstThePixel/com.utilities.buildpipeine
